sudo: false
arch:
    - amd64
    - ppc64le
language: node_js
node_js:
 -  8
 - 10
 - 12
 - 14
 - 15
 - lts/*
 - node
env:
 - DEFAULT_NODE_VERSION=12

script:
  - npm run lint
  - npm run mocha -- --timeout 500
  - npm run spec-turtle
  - npm run spec-ntriples
  - npm run spec-nquads
  - npm run spec-trig
  - if [ "$TRAVIS_NODE_VERSION" != "8" ]; then
      npm run docs;
    fi

after_success:
  - if [ "$TRAVIS_NODE_VERSION" == "$DEFAULT_NODE_VERSION" ]; then
      npm install coveralls;
      node_modules/.bin/nyc --reporter=text-lcov npm run mocha |
        node_modules/.bin/coveralls;
      ./.travis_build_pages;
    fi

cache:
  - npm
  - directories:
    - .rdf-test-suite-cache

jobs:
  allow_failures:
    - node_js: 15
    - node_js: node
